### ISSUE TITLE
json import errors after 3.0.0 update

### ISSUE THREAD

**Issue by madisp** [FortAwesome/react-fontawesome#589]
After bumping to 3.0.0 I'm getting

```
TypeError: Module "file:///.../node_modules/@fortawesome/fontawesome-svg-core/package.json" needs an import attribute of "type: json"
```

when running a test with `vitest` on a file that imports `@fortawesome/react-fontawesome`.
I'm guessing it has something to do with the import here?

https://github.com/FortAwesome/react-fontawesome/blob/7e7375b355817703fcdb622c70717eab0529cb6c/src/utils/constants.ts#L6

**Comment by matys1** [comment]
Same issue!

**Comment by stevensacks** [comment]
This error also happens in vitest.

**Comment by stevensacks** [comment]
Even with the above workaround, React Router 7 throws this error on the server-side and crashes the app:
```ts
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://react.dev/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useId')
    at process.env.NODE_ENV.exports.useId (/Users/stevensacks/Development/gaia/framework/remix/node_modules/.vite/deps_ssr/@fortawesome_react-fontawesome.js?v=4724c82c:1348:35)
    at useAccessibilityId (/Users/stevensacks/Development/gaia/framework/remix/node_modules/.vite/deps_ssr/@fortawesome_react-fontawesome.js?v=4724c82c:7328:46)
    at FontAwesomeIcon (/Users/stevensacks/Development/gaia/framework/remix/node_modules/.vite/deps_ssr/@fortawesome_react-fontawesome.js?v=4724c82c:7535:18)
    at Object.react_stack_bottom_frame (/Users/stevensacks/Development/gaia/framework/remix/node_modules/react-dom/cjs/react-dom-server.node.development.js:9176:18)
    at renderWithHooks (/Users/stevensacks/Development/gaia/framework/remix/node_modules/react-dom/cjs/react-dom-server.node.development.js:4797:19)
    at renderElement (/Users/stevensacks/Development/gaia/framework/remix/node_modules/react-dom/cjs/react-dom-server.node.development.js:5631:39)
    at retryNode (/Users/stevensacks/Development/gaia/framework/remix/node_modules/react-dom/cjs/react-dom-server.node.development.js:5991:31)
    at renderNodeDestructive (/Users/stevensacks/Development/gaia/framework/remix/node_modules/react-dom/cjs/react-dom-server.node.development.js:5941:11)
    at renderNode (/Users/stevensacks/Development/gaia/framework/remix/node_modules/react-dom/cjs/react-dom-server.node.development.js:6398:18)
    at renderElement (/Users/stevensacks/Development/gaia/framework/remix/node_modules/react-dom/cjs/react-dom-server.node.development.js:5358:18)
```

**Comment by charles4221** [comment]
@madisp @matys1 @stevensacks @jeremy-step @ken717w @zedd3v @GabeMeister 

I have just published `3.0.1` to both public and PRO registries, please install and see if this resolves the issues for you all 🙏🏻

**Comment by stevensacks** [comment]
**3.0.1 Testing**

Without the ssr noExternal setting, this warning is outputted, but the app runs successfully:
```
[react-fontawesome] Error loading SVGCore version: TypeError [ERR_IMPORT_ATTRIBUTE_MISSING]: Module "file:///Users/stevensacks/Development/gaia/framework/remix/node_modules/@fortawesome/fontawesome-svg-core/package.json" needs an import attribute of "type: json"
```
With this in vite.config.ts and vitest.config.ts, the warning goes away:
```ts
ssr: {
    noExternal: ['@fortawesome/react-fontawesome'],
}
```

**Comment by acelaya** [comment]
> I have just published `3.0.1` to both public and PRO registries, please install and see if this resolves the issues for you all 🙏🏻

I can confirm things work for me with v3.0.1, although the warning is still printed when using vite, and I can't seem to be able to silence it with the configuration proposed above by others.

Not the end of the world though.

**Comment by matys1** [comment]
@charles4221 after upgrading to 3.0.1 and removing the `ssr: { noExternal: ["@fortawesome/react-fontawesome"] }` from my vite.config.ts I still see this in my terminal output:

```
```

**Comment by charles4221** [comment]
To resolve this issue once and for all, I have refactored this piece again so that we can achieve the same functionality of differentiating between consumers using SVG Core v6 versus v7 but without directly importing the `package.json` file.

https://github.com/FortAwesome/react-fontawesome/pull/593

**Comment by charles4221** [comment]
Hi all, this is now fixed properly in [v3.0.2](https://github.com/FortAwesome/react-fontawesome/releases/tag/v3.0.2)
